apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: abhirup18/spe_backend
          ports:
            - name: http
              containerPort: 9002
          env:
            - name: MONGO
              value: "mongodb+srv://abhirupchakraborty1998:cms1998@cluster0.nld22m2.mongodb.net/CMS-db?retryWrites=true&w=majority"
            - name: PORT
              value: "9002"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 9002
      targetPort: 9002
      # nodePort: 30001